FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine AS base
WORKDIR /app
EXPOSE 2626

FROM mcr.microsoft.com/dotnet/sdk:6.0.100-preview.2-bullseye-slim-amd64 AS build
COPY . .
RUN dotnet build "MoraES.Server/MoraES.Server.csproj" -c Release -o /app/build --runtime alpine-x64

FROM build AS publish
RUN dotnet publish "MoraES.Server/MoraES.Server.csproj" -c Release -o /app/publish  --runtime alpine-x64 \
    --self-contained true \
    /p:PublishTrimmed=true \
    /p:PublishSingleFile=true

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["./MoraES.Server"]