FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
COPY . .
RUN dotnet build "MoraES.Client/MoraES.Client.csproj" -c Release -o /app/build --runtime alpine-x64

FROM build AS publish
RUN dotnet publish "MoraES.Client/MoraES.Client.csproj" -c Release -o /app/publish  --runtime alpine-x64 \
    --self-contained true \
    /p:PublishTrimmed=true \
    /p:PublishSingleFile=true

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["./MoraES.Client"]